#include <Arduino.h>
// Include IMU drivers and configs
#include "../config/imu_configs/BMI088Config.h"
#include "../config/imu_configs/BNO055Config.h"
#include "../config/imu_configs/BMI160Config.h"
#include "../config/motor_configs/motor_common_config.h"
#include "imu_drivers/BMI088Driver.h"
#include "imu_drivers/BNO055Driver.h"
#include "imu_drivers/BMI160Driver.h"
#include "imu_drivers/imu_manager.h"
#include "SystemTasks.h"
#include "btle_hid.h"
#include "imu_calibration.h"
#include "logging.h"
#include "motor_drivers/driver_manager.h"
#include "serial_commands.h"
#include <ArduinoOTA.h>

// Select IMU driver at compile time (0 = BMI088, 1 = BNO055, 2 = BMI160)
#ifndef IMU_SELECTION
#define IMU_SELECTION 2
#endif

#if IMU_SELECTION == 1
static abbot::BNO055Config imu_cfg;
static abbot::BNO055Driver imu_driver(imu_cfg);
#elif IMU_SELECTION == 2
static abbot::BMI160Config imu_cfg;
static abbot::BMI160Driver imu_driver(imu_cfg);
#else
static abbot::BMI088Config imu_cfg;
static abbot::BMI088Driver imu_driver(imu_cfg);
#endif

void setup() {
  Serial.begin(921600);
  // Initialize logging subsystem early so boot-time LOG_* calls are effective
  abbot::log::init();
  // Ensure tuning stream is off by default at boot
  abbot::log::disableChannel(abbot::log::CHANNEL_TUNING);
  // Print calibration values if present
  {
    abbot::imu_cal::Calibration cal;
    if (abbot::imu_cal::loadCalibration(cal)) {
      LOG_PRINTF(abbot::log::CHANNEL_DEFAULT,
                 "Calibration loaded: gyro_bias=%.6f,%.6f,%.6f\n",
                 cal.gyro_bias[0], cal.gyro_bias[1], cal.gyro_bias[2]);
      LOG_PRINTF(abbot::log::CHANNEL_DEFAULT,
                 "Calibration loaded: accel_offset=%.6f,%.6f,%.6f\n",
                 cal.accel_offset[0], cal.accel_offset[1], cal.accel_offset[2]);
      // Install into the imu_cal module so `CALIB DUMP` reports these values
      abbot::imu_cal::installCalibration(cal);
    } else {
      LOG_PRINTLN(abbot::log::CHANNEL_DEFAULT, "No IMU calibration found");
    }
  }
  // initialize IMU driver
  bool ok = imu_driver.begin();
  if (!ok) {
    LOG_PRINTF(abbot::log::CHANNEL_DEFAULT, "%s init failed! Check wiring/address.\n", imu_driver.getDriverName());
  } else {
    LOG_PRINTF(abbot::log::CHANNEL_DEFAULT, "%s initialized\n", imu_driver.getDriverName());
    abbot::imu::setActiveIMUDriver(&imu_driver);

    // Only start producer/consumer if IMU is healthy
    if (abbot::startIMUTasks(&imu_driver)) {
      LOG_PRINTLN(abbot::log::CHANNEL_DEFAULT, "IMU tasks started");
    } else {
      LOG_PRINTLN(abbot::log::CHANNEL_DEFAULT, "Failed to start IMU tasks");
    }
  }

  // Install default motor driver selected via manager/config and initialize
  abbot::motor::installDefaultMotorDriver();
  // Diagnostic heartbeat to verify serial output during boot
  LOG_PRINTLN(abbot::log::CHANNEL_DEFAULT,
              "BOOT DEBUG: setup complete, entering main loop");

  // Show interactive serial menu at boot
  abbot::serialcmds::startInteractiveMenu(&imu_driver);

  // Start BLE HID client (Xbox / BLE HID controllers). warning: blocking call
  abbot::btle_hid::begin();

  // Initialize OTA for WiFi updates
  ArduinoOTA.setHostname("AutoBalancingBot");
  ArduinoOTA.begin();
}

void loop() {
  // Process OTA requests if WiFi is connected
  if (WiFi.status() == WL_CONNECTED) {
    ArduinoOTA.handle();
  }
  
  // Process serial commands (motor, IMU, etc.) generated by BLE HID or user
  abbot::serialcmds::processSerialOnce(&imu_driver);
  delay(10);
}
